In [129]:
import pandas as pd
import numpy as np

In [163]:
data = {
    "Name": [
        "Rahul", "Priya", "Amit", "rahul ", "Neha",
        "Vikas", "Priya", "Rohan", "Sneha", "Amit"
    ],
    
    "Age": [
        22, np.nan, 25, 22, "twenty-four",
        -5, np.nan, 30, 150, 25
    ],
    
    "City": [
        "Lucknow", "lucknow", "Delhi", "Lucknow ",
        "DELHI", "Kanpur", "Lucknow", "Delhi", "delhi", "Delhi"
    ],
    
    "Gender": [
        "Male", "Female", "M", "male", "F",
        "Female", "female", "Male", "F", "Male"
    ],
    
    "Salary": [
        35000, 42000, np.nan, 35000, 50000,
        38000, 42000, "45000", 48000, 45000
    ],
    
    "Joining_Date": [
        "2022-01-15", "15/02/2021", "2020-03-10", "2022-01-15",
        "invalid_date", "2023/05/20", "15-02-2021", "2021-12-01",
        "2020-13-40", "2020-03-10"
    ]
}

df = pd.DataFrame(data)

df

     Name          Age      City  Gender Salary  Joining_Date
0   Rahul           22   Lucknow    Male  35000    2022-01-15
1   Priya          NaN   lucknow  Female  42000    15/02/2021
2    Amit           25     Delhi       M    NaN    2020-03-10
3  rahul            22  Lucknow     male  35000    2022-01-15
4    Neha  twenty-four     DELHI       F  50000  invalid_date
5   Vikas           -5    Kanpur  Female  38000    2023/05/20
6   Priya          NaN   Lucknow  female  42000    15-02-2021
7   Rohan           30     Delhi    Male  45000    2021-12-01
8   Sneha          150     delhi       F  48000    2020-13-40
9    Amit           25     Delhi    Male  45000    2020-03-10

## clean invalid value

In [131]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          10 non-null     str
 1   Age           8 non-null      object
 2   City          10 non-null     str
 3   Gender        10 non-null     str
 4   Salary        9 non-null      object
 5   Joining_Date  10 non-null     str
dtypes: object(2), str(4)
memory usage: 612.0+ bytes

In [132]:
df.describe()
df.isnull().sum()

Name            0
Age             2
City            0
Gender          0
Salary          1
Joining_Date    0
dtype: int64

In [133]:
df['Age'].value_counts(dropna=False)

# df[df['Age'] < 0]
# df[df['Age'] > 100]

Age
22             2
NaN            2
25             2
twenty-four    1
-5             1
30             1
150            1
Name: count, dtype: int64

In [134]:
invalid_row = df[df['Age'] == 'twenty-four']
idx = invalid_row.index.start
df.loc[idx, 'Age'] = 24
print(df['Age'].dtypes)
df['Age']

object

0     22
1    NaN
2     25
3     22
4     24
5     -5
6    NaN
7     30
8    150
9     25
Name: Age, dtype: object

In [135]:
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
print(df['Age'].dtypes)

float64

In [136]:
df.loc[df['Age'] < 0, 'Age'] = np.nan

df.loc[df['Age'] > 100, 'Age'] = np.nan

In [137]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Age'].isnull().sum()

np.int64(0)

In [138]:
df.isnull().sum()

Name            0
Age             0
City            0
Gender          0
Salary          1
Joining_Date    0
dtype: int64

## clean duplicate value

In [139]:
df.duplicated().sum()
df[df.duplicated()]

Empty DataFrame
Columns: [Name, Age, City, Gender, Salary, Joining_Date]
Index: []

In [140]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [Name, Age, City, Gender, Salary, Joining_Date]
Index: []

In [141]:
test_df = pd.concat([df, df.iloc[[0]]], ignore_index=True)

In [142]:
test_df.duplicated().sum()
test_df[test_df.duplicated(keep=False)]
test_df = test_df.drop_duplicates()

In [143]:
test_df

     Name   Age      City  Gender Salary  Joining_Date
0   Rahul  22.0   Lucknow    Male  35000    2022-01-15
1   Priya  24.5   lucknow  Female  42000    15/02/2021
2    Amit  25.0     Delhi       M    NaN    2020-03-10
3  rahul   22.0  Lucknow     male  35000    2022-01-15
4    Neha  24.0     DELHI       F  50000  invalid_date
5   Vikas  24.5    Kanpur  Female  38000    2023/05/20
6   Priya  24.5   Lucknow  female  42000    15-02-2021
7   Rohan  30.0     Delhi    Male  45000    2021-12-01
8   Sneha  24.5     delhi       F  48000    2020-13-40
9    Amit  25.0     Delhi    Male  45000    2020-03-10

## String Cleaning

In [144]:
df['City'].value_counts()
df['City'] = df['City'].str.strip()
df['City'] = df['City'].str.lower()

df['City'].value_counts()
df["City"].unique()

<StringArray>
['lucknow', 'delhi', 'kanpur']
Length: 3, dtype: str

In [145]:
df["Gender"].unique() # ['Male', 'Female', 'M', 'male', 'F', 'female']
df["Gender"].value_counts()

Gender
Male      3
Female    2
F         2
M         1
male      1
female    1
Name: count, dtype: int64

In [146]:
df['Gender'] = df['Gender'].replace({
    'M': 'Male',
    'male': 'Male',
    'female': 'Female',
    'F': 'Female'
})
df['Gender'].value_counts()

Gender
Male      5
Female    5
Name: count, dtype: int64

In [147]:
df["Name"].unique()

df['Name'] =  df['Name'].str.strip().str.title()

df['Name'].value_counts()

Name
Rahul    2
Priya    2
Amit     2
Neha     1
Vikas    1
Rohan    1
Sneha    1
Name: count, dtype: int64

## Date / Time Cleaning

In [148]:
df['Joining_Date']

0      2022-01-15
1      15/02/2021
2      2020-03-10
3      2022-01-15
4    invalid_date
5      2023/05/20
6      15-02-2021
7      2021-12-01
8      2020-13-40
9      2020-03-10
Name: Joining_Date, dtype: str

In [149]:
print(df["Joining_Date"].dtype) # str

df["Joining_Date"] = pd.to_datetime(
    df["Joining_Date"],
    errors="coerce"
)


df['Joining_Date']

str

0   2022-01-15
1          NaT
2   2020-03-10
3   2022-01-15
4          NaT
5          NaT
6          NaT
7   2021-12-01
8          NaT
9   2020-03-10
Name: Joining_Date, dtype: datetime64[us]

In [152]:
print(df["Joining_Date"].dtype)
df["Joining_Date"].dt.year
df["Joining_Date"].dt.month

datetime64[us]

0     1.0
1     NaN
2     3.0
3     1.0
4     NaN
5     NaN
6     NaN
7    12.0
8     NaN
9     3.0
Name: Joining_Date, dtype: float64

In [ ]:
dates = pd.Series(["15/02/2021", "20/03/2022", "05/11/2023"])
dates = pd.to_datetime(dates, format='%d/%m/%Y')
print(dates.dtypes)

datetime64[us]

In [165]:
df['Joining_Date'] = pd.to_datetime(
    df['Joining_Date'],
    format="mixed",
    errors="coerce"
)
df

     Name          Age      City  Gender Salary Joining_Date
0   Rahul           22   Lucknow    Male  35000   2022-01-15
1   Priya          NaN   lucknow  Female  42000   2021-02-15
2    Amit           25     Delhi       M    NaN   2020-03-10
3  rahul            22  Lucknow     male  35000   2022-01-15
4    Neha  twenty-four     DELHI       F  50000          NaT
5   Vikas           -5    Kanpur  Female  38000   2023-05-20
6   Priya          NaN   Lucknow  female  42000   2021-02-15
7   Rohan           30     Delhi    Male  45000   2021-12-01
8   Sneha          150     delhi       F  48000          NaT
9    Amit           25     Delhi    Male  45000   2020-03-10

In [169]:
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')
df['Salary'] = df['Salary'].fillna(df['Salary'].median())
df

     Name          Age      City  Gender   Salary Joining_Date
0   Rahul           22   Lucknow    Male  35000.0   2022-01-15
1   Priya          NaN   lucknow  Female  42000.0   2021-02-15
2    Amit           25     Delhi       M  42000.0   2020-03-10
3  rahul            22  Lucknow     male  35000.0   2022-01-15
4    Neha  twenty-four     DELHI       F  50000.0          NaT
5   Vikas           -5    Kanpur  Female  38000.0   2023-05-20
6   Priya          NaN   Lucknow  female  42000.0   2021-02-15
7   Rohan           30     Delhi    Male  45000.0   2021-12-01
8   Sneha          150     delhi       F  48000.0          NaT
9    Amit           25     Delhi    Male  45000.0   2020-03-10

In [ ]:
df['Salary'].isnull().sum()
df['Salary'].dtype

dtype('float64')